# zabbix server authentication
server = "https://mon.intern.zone35.de"
username = "Admin"
password = "KJNNhG53hqf6mPuG8NbLwM85vnAHCl9a"

# logging levels: debug, info, warning, error
# log-level = "warning"

# filter types of alerts
item-types = ["down", "unack"]

# minimum trigger severities: unknown, information, warning, average, high, critical
min-severity = "information"

# refresh data every N seconds
refresh = 1

# enable notifications
# notify = true
